# Generated by Django 2.2 on 2019-05-01 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 1, 14, 47, 54, 103891))),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
