# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tv_series_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_series', models.CharField(blank=True, max_length=150, null=True)),
                ('genre', models.CharField(max_length=150, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('released', models.CharField(max_length=150, null=True)),
                ('imdb_rating', models.CharField(max_length=150, null=True)),
                ('poster', models.URLField(null=True)),
                ('seasons', models.CharField(max_length=150, null=True)),
                ('trailer', models.URLField(null=True)),
                ('last_season_released_date', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tv_series',
        ),
    ]
