# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0002_auto_20190402_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_series_list',
            name='last_season_released_date',
        ),
    ]
