# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games_list',
            name='artist',
        ),
        migrations.AddField(
            model_name='games_list',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
