# Generated by Django 2.0.5 on 2019-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, max_length=150, null=True)),
                ('genre', models.CharField(max_length=150, null=True)),
                ('artist', models.CharField(max_length=150, null=True)),
                ('released', models.CharField(max_length=150, null=True)),
                ('rating', models.CharField(max_length=150, null=True)),
                ('poster', models.URLField(null=True)),
                ('developer', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
